"""
billing_registry.py: the versioned registry of what billing activation needs, per payer workflow.

Every requirement has a documented source and its dependencies. Nothing here is generated by AI, and AI never adds
to it: a person edits this file, bumps VERSION, and fills in REVIEW once someone has checked the entries against the
sources. Until then the screens say the registry hasn't been reviewed, and clinics should confirm details with each
payer. Payer rules change; this file records what we could source, not a promise about any payer's process.

Scopes (where a requirement's status is stored):
  clinic     the practice as a whole (its authorization, its clearinghouse account)
  entity     the billing entity (the Tax ID / organization NPI that gets paid)
  provider   one rendering practitioner (individual NPI)
  location   one service location
  payer      the requirement applies per payer (combined with entity or provider scope)

Tracks (kept separate on purpose, because each moves on its own timeline):
  identity       NPI / Tax ID / license facts
  authorization  the clinic's own approval for Althais to act
  enrollment     payer provider/group enrollment
  credentialing  payer credentialing
  contracting    payer participation agreement (in-network)
  edi            electronic claim (837P) submission enrollment
  era            electronic remittance (835) enrollment (payment, doesn't block sending claims)
  eft            electronic funds transfer (payment, doesn't block sending claims)
  connectivity   the clinic's clearinghouse account and payer route
"""

VERSION = "2026.09.1"
REVIEW = {"reviewedBy": None, "reviewedOn": None}   # filled in by a person after checking every source below

PAYER_TYPES = {"medicare": "Medicare (Part B)", "medicaid": "Medicaid", "commercial": "Commercial / Medicare Advantage", "other": "Other"}
KNOWN_PAYERS = {
    "medicare": ("Medicare", "medicare"), "medicaid": ("Medicaid", "medicaid"),
    "unitedhealthcare": ("UnitedHealthcare", "commercial"), "aetna": ("Aetna", "commercial"),
    "bluecross blueshield": ("BlueCross BlueShield", "commercial"), "bcbs": ("BlueCross BlueShield", "commercial"),
    "cigna": ("Cigna", "commercial"), "humana": ("Humana", "commercial"),
}

_NPPES = ("NPPES NPI Registry (CMS)", "https://nppes.cms.hhs.gov/")
_IRS_EIN = ("IRS: Employer ID Numbers", "https://www.irs.gov/businesses/small-businesses-self-employed/employer-id-numbers")
_IRS_W9 = ("IRS: About Form W-9", "https://www.irs.gov/forms-pubs/about-form-w-9")
_PECOS = ("CMS PECOS (Medicare enrollment)", "https://pecos.cms.hhs.gov/")
_CMS855B = ("CMS-855B form", "https://www.cms.gov/medicare/cms-forms/cms-forms/downloads/cms855b.pdf")
_CMS855I = ("CMS-855I form", "https://www.cms.gov/medicare/cms-forms/cms-forms/downloads/cms855i.pdf")
_CMS588 = ("CMS-588 EFT authorization form", "https://www.cms.gov/medicare/cms-forms/cms-forms/downloads/cms588.pdf")
_MAC = ("Your Medicare Administrative Contractor's EDI enrollment page", "")
_CAQH = ("CAQH ProView", "https://proview.caqh.org/")
_MEDICAID = ("Medicaid.gov: state Medicaid agencies", "https://www.medicaid.gov/")
_PAYER = ("The payer's provider enrollment team or portal", "")
_CH = ("Your clearinghouse's payer list and enrollment rules", "")
_ALTHAIS = ("Althais billing activation (internal)", "")


def _r(rid, title, scope, track, payer_types, source, depends=(), evidence="", verify="", prefill=(), sign=None, blocks_claims=True,
       supported=True, note=""):
    return {"id": rid, "title": title, "scope": scope, "track": track, "payerTypes": list(payer_types), "dependsOn": list(depends),
            "source": {"title": source[0], "url": source[1]}, "evidence": evidence, "verify": verify, "prefill": list(prefill),
            "signature": sign, "blocksClaims": blocks_claims, "supported": supported, "note": note}


ALL = ("medicare", "medicaid", "commercial", "other")
REQUIREMENTS = [
    # the practice itself
    _r("clinic_authorization", "Owner authorizes Althais to prepare enrollments and send claims", "clinic", "authorization", ALL, _ALTHAIS,
       evidence="Signed in Althais by a clinic owner or admin", sign="owner"),
    _r("clearinghouse_account", "Clearinghouse account connected", "clinic", "connectivity", ALL, _CH, depends=("clinic_authorization",),
       evidence="A successful connection check from the clearinghouse (or its written confirmation)", verify="clearinghouse"),
    # the billing entity
    _r("entity_npi", "Organization NPI (Type 2) is active", "entity", "identity", ALL, _NPPES,
       evidence="NPI Registry lookup", verify="nppes", prefill=("npi", "legal_name")),
    _r("entity_tin", "Tax ID confirmed", "entity", "identity", ALL, _IRS_EIN,
       evidence="IRS letter (CP 575 or 147C) or a signed W-9 matching the legal name", prefill=("tin", "legal_name")),
    _r("entity_w9", "Signed W-9 on file", "entity", "identity", ("commercial", "medicaid", "other"), _IRS_W9, depends=("entity_tin",),
       evidence="W-9 signed by the clinic", blocks_claims=False),
    # each rendering provider
    _r("provider_npi", "Individual NPI (Type 1) is active", "provider", "identity", ALL, _NPPES,
       evidence="NPI Registry lookup", verify="nppes", prefill=("npi", "name", "taxonomy")),
    _r("provider_license", "State license is current", "provider", "identity", ALL, ("The state licensing board", ""),
       evidence="License document with a future expiration date, checked by a person", prefill=("license_number", "state", "expires")),
    # Medicare
    _r("medicare_group", "Medicare enrollment for the group (CMS-855B, through PECOS)", "entity", "enrollment", ("medicare",), _PECOS,
       depends=("entity_npi", "entity_tin"), evidence="Approval letter with the effective date and PTAN", prefill=("legal_name", "npi", "tin", "address"),
       sign="owner", note=f"Form: {_CMS855B[1]}"),
    _r("medicare_provider", "Medicare enrollment for the practitioner, with benefits reassigned to the group (through PECOS)", "provider", "enrollment",
       ("medicare",), _PECOS, depends=("provider_npi", "medicare_group"), evidence="Approval letter with the effective date",
       prefill=("name", "npi", "license_number"), sign="provider", note=f"Form: {_CMS855I[1]}"),
    _r("medicare_edi", "Electronic claims enrollment with your Medicare contractor (MAC), naming your clearinghouse", "entity", "edi", ("medicare",),
       _MAC, depends=("medicare_group", "clearinghouse_account"), evidence="MAC EDI enrollment confirmation", sign="owner"),
    _r("medicare_era", "Electronic remittance (835) enrollment with your MAC", "entity", "era", ("medicare",), _MAC, depends=("medicare_edi",),
       evidence="MAC confirmation", blocks_claims=False),
    _r("medicare_eft", "Electronic funds transfer (CMS-588)", "entity", "eft", ("medicare",), _CMS588, depends=("medicare_group",),
       evidence="CMS-588 accepted", sign="owner", blocks_claims=False),
    # Medicaid: state programs differ, so Althais doesn't prefill these yet
    _r("medicaid_group", "State Medicaid enrollment for the group", "entity", "enrollment", ("medicaid",), _MEDICAID, depends=("entity_npi", "entity_tin"),
       evidence="State approval letter with the effective date", supported=False, note="Each state runs its own enrollment. Althais tracks it; you submit it."),
    _r("medicaid_provider", "State Medicaid enrollment for the practitioner", "provider", "enrollment", ("medicaid",), _MEDICAID,
       depends=("provider_npi", "medicaid_group"), evidence="State approval letter with the effective date", supported=False),
    _r("medicaid_edi", "Electronic claims enrollment with the state Medicaid program", "entity", "edi", ("medicaid",), _MEDICAID,
       depends=("medicaid_group", "clearinghouse_account"), evidence="State or clearinghouse confirmation", supported=False),
    # commercial and Medicare Advantage plans
    _r("commercial_credentialing", "Credentialing with the payer (most use a CAQH ProView profile)", "provider", "credentialing", ("commercial",), _CAQH,
       depends=("provider_npi", "provider_license"), evidence="Payer's credentialing approval with the effective date", prefill=("name", "npi"),
       sign="provider"),
    _r("commercial_contract", "Participation agreement with the payer (in-network)", "entity", "contracting", ("commercial",), _PAYER,
       depends=("entity_npi", "entity_tin"), evidence="Signed agreement or welcome letter with the effective date", sign="owner",
       note="Only needed to bill in-network. A clinic can mark a payer as out-of-network, with a person confirming that."),
    _r("commercial_edi", "Electronic claims (837P) enrollment, if the payer requires it", "entity", "edi", ("commercial",), _CH,
       depends=("clearinghouse_account",), evidence="Clearinghouse payer list showing enrollment isn't required, or the payer's approval",
       verify="clearinghouse"),
    _r("commercial_era", "Electronic remittance (835) enrollment", "entity", "era", ("commercial",), _CH, depends=("commercial_edi",),
       evidence="Payer or clearinghouse confirmation", blocks_claims=False),
    # other payers: tracked, never assumed
    _r("other_enrollment", "Enrollment with the payer", "entity", "enrollment", ("other",), _PAYER, evidence="Payer approval with the effective date",
       supported=False),
    _r("other_edi", "Electronic claims enrollment, if the payer requires it", "entity", "edi", ("other",), _CH, depends=("clearinghouse_account",),
       evidence="Clearinghouse payer list or payer approval", supported=False),
]
BY_ID = {r["id"]: r for r in REQUIREMENTS}


def payer_type(name: str) -> str:
    return KNOWN_PAYERS.get((name or "").strip().lower(), (name, "other"))[1]


def payer_key(name: str) -> str:
    n = (name or "").strip()
    return KNOWN_PAYERS.get(n.lower(), (n, ""))[0].lower().replace(" ", "_") or "unknown"


def for_payer(ptype: str) -> list:
    return [r for r in REQUIREMENTS if ptype in r["payerTypes"] and r["scope"] in ("entity", "provider") and r["track"] not in ("identity",)
            and r["id"] not in ("entity_w9",)]


def common(scope: str) -> list:
    """Requirements that don't depend on a payer (clinic, entity and provider identity)."""
    return [r for r in REQUIREMENTS if r["scope"] == scope and (r["track"] in ("identity", "authorization", "connectivity"))]
